<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

use App\Http\ApiV1\Modules\Feedbacks\Controllers\FeedbacksController;
use Illuminate\Support\Facades\Route;

Route::post('feedbacks/feedbacks', [FeedbacksController::class, 'create']);
Route::get('feedbacks/feedbacks/{id}', [FeedbacksController::class, 'get']);
