openapi: 3.0.3
info:
  title: Feedbacks
  version: 1.0.0
  description: Feedbacks service
servers:
  - url: /api/v1
tags:
  - name: feedbacks
    description: Feedbacks
paths:
  /feedbacks/feedbacks:
    $ref: './feedbacks/paths.yaml#/Feedbacks'
  /feedbacks/feedbacks/{id}:
    $ref: './feedbacks/paths.yaml#/FeedbacksOne'
components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
        - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'